### PR TITLE
export a api for modify username and password to use dynamic login me…

### PR DESCRIPTION
**Pull request by congleetea**
export a api for modify username and password to use dynamic login  method

### CODE REVIEW

**Comment by robertzhouxh** [comment]
i think it is better to save the password hash value into a file, not env

**Comment by congleetea** [comment]
I have modified it , please check it.

**Comment by congleetea** [comment]
Now, I  change the directory  saving the usename and password file  to make sure that user not need to reset username and password after recompiled.

**Comment by robertzhouxh** [comment]
cool

**Pull request merged**
